# Generated by Django 3.2.16 on 2024-05-13 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-id',), 'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
    ]
